mutation commitDocumentFileReplace($document: _UpdatePdsContractInput!, $compare: _ComparePdsContractInput!, $previous: _UpdatePdsContractVersionInput!, $file: _CreateAttachmentInput!, $retired: _UpdateAttachmentInput!, $command: _CreateDocumentCommandInput!) { packet { updatePdsContract(input: $document, compare: $compare) { id } updatePdsContractVersion(input: $previous) { id } createAttachment(input: $file) { id } updateAttachment(input: $retired) { id } createDocumentCommand(input: $command) { id } } }
