mutation replaceAttachmentVersion($currentAttachmentId: ID!, $input: _CreateAttachmentInput!, $changeId: String!, $contractId: ID!, $change: _CreateAttachmentChangeInput!) { packet { updateAttachment(input: { id: $currentAttachmentId, current: false }) { id attachmentId logicalAttachmentId documentId version current } createAttachment(input: $input) { id attachmentId logicalAttachmentId documentId fileName contentType size storageReference version current uploadedAt } createAttachmentChange(input: $change) { id } updatePdsContract(input: { id: $contractId, attachmentsHead: $changeId }) { id } } }
